# This is a basic workflow to help you get started with Actions

name: Generate AdGuardHome rules

# Controls when the workflow will run
on:
  schedule:
    - cron: '11 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Generate AdGuardHome rules
        run: |
          ls >> log.log
          chmod +x ../../gfwlist2adguardhome.sh >> log.log
          bash ../../gfwlist2adguardhome.sh -s 8.8.4.4 >> log.log
          echo log.log

      # Upload adguardhome_gfwlist.txt
      - uses: actions/upload-artifact@v2
        with:
          name: adguardhome_gfwlist.txt
          path: adguardhome_gfwlist.txt